language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

env:
  global:
     - SYMFONY_DEPRECATIONS_HELPER="/.*each.*/"
     - SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
     - SYMFONY_PHPUNIT_VERSION=5.7

matrix:
  matrix: SYMFONY_VERSION=4.0.*
  include:
    - php: 7.2
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" REQUIREMENTS="phpcr/phpcr:2.1.2"
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$REQUIREMENTS" != "" ]; then composer require --no-update $REQUIREMENTS; fi
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi

install: travis_wait composer update --prefer-dist $COMPOSER_FLAGS

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
